console.log("Hola, JavaScript");
console.log("Estoy preparando mi primera Pokédex");
console.log("Durante el curso utilizaremos JavaScript y TypeScript");
const nombre = "Charmander";
const tipo = "fuego";
const nivel = 8;
console.log(nombre);
console.log(tipo);
console.log(nivel);
console.log(`${nombre} es de tipo ${tipo} y tiene nivel ${nivel}.`);